services:

  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "" # Empty password for root user
      MYSQL_DATABASE: test # Database name 'test'
      MYSQL_USER: root # User is 'root'
      MYSQL_PASSWORD: "" # Empty password for root
    volumes:
      - mysql_data:/var/lib/mysql # Persistent storage for MySQL data
    ports:
      - "3306:3306" # Expose MySQL port
    restart: always

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql # Hostname for MySQL service
      PMA_USER: root # User to login to phpMyAdmin (root)
      PMA_PASSWORD: "" # Empty password for root in phpMyAdmin
    ports:
      - "8081:80" # Expose phpMyAdmin on port 8080
    depends_on:
      - mysql # Ensure MySQL starts before phpMyAdmin
    restart: always

volumes:
  mysql_data: # Docker volume for MySQL data persistence
